# Generated by Django 3.2.13 on 2022-12-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='campus',
        ),
    ]
