import { useState, useEffect } from "react";

import Head from "next/head";
import Router from "next/router";

import LargeText from "../common/LargeText";
import MainButton from "../common/MainButton";
import IndexAnimation from "../component/IndexAnimation";
import styled from "styled-components";
import { getKeyCookies } from '../modules/cookie/keyCookies';

export default function Home() {
  const route = Router;

  useEffect(() => {
    if (getKeyCookies("key") !== undefined) {
      route.push('/login/after')
    }
  }, []);

  // 크로스 브라우징 높이, 넓이 계산
  let vh = 0;
  let vw = 0;
  useEffect(() => {
    vh = window.innerHeight * 0.01;
    vw = window.innerWidth * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);
    document.documentElement.style.setProperty("--vw", `${vw}px`);
  }, []);

  const moveToLogin = () => {
    route.push("/login");
  };

  const moveToSignup = () => {
    route.push("/signup");
  };

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <IndexBox>
          <TitleBox>
            <IndexAnimation />
            <LargeText> SSEEKER</LargeText>
          </TitleBox>
          <ButtonBox>
            <MainButton onButtonClick={moveToLogin}> LogIn</MainButton>
            <MainButton onButtonClick={moveToSignup}> SignUp</MainButton>
          </ButtonBox>
        </IndexBox>
      </main>
    </>
  );
}

const IndexBox = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  height: calc(var(--vh, 1vh) * 100);
  width: 100vw;
  width: calc(vat(--vw, 1vw) * 100);
`;

const TitleBox = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: auto;
`;

const ButtonBox = styled.div`
  display: flex;
  flex-direction: column;
  margin: 0px 15px;
  margin-top: auto;
`;
