import {useState} from "react";

import Head from "next/head";
import Router from 'next/router';

import TitleText from "../common/TitleText";
import MainButton from '../common/MainButton';
import Menu from "../common/Menu";
import MenuBox from "../component/MenuBox";
import StackIcon from "../common/StackIcon"
import ClassSelect from '../common/ClassSelect';
import CardList from '../component/CardList';
import IndexAnimation from '../component/IndexAnimation';


export default function Home() {
    const [menuOpen, setMenuOpen] = useState<boolean>(false);
    const route = Router;

    const moveToLogin = () => {
        route.push('/login');
    }

    const moveToSignup = () => {
        route.push('/signup');
    }

    return (
        <>
          <Head>
            <meta name = 'description' content = 'Generated by create next app' />
            <meta name = 'viewport' content = 'width=device-width, initial-scale=1' />
            <link rel = 'icon' href = '/favicon.ico' />
            
          </Head>
          <main>
            <IndexAnimation />
            <TitleText> SSEEKER</TitleText>
            <MainButton onButtonClick = {moveToLogin}> LogIn</MainButton>
            <MainButton onButtonClick = {moveToSignup} > SignUp</MainButton>
            <ClassSelect></ClassSelect> 
            <Menu menuOpen = {menuOpen} setMenuOpen = {setMenuOpen} />
            <MenuBox menuOpen = {menuOpen} />
            <StackIcon stack={"django"} />
            <StackIcon stack={"fastapi"} />
            <CardList></CardList>
          </main>
        </>
    );
}
