# Generated by Django 3.2.13 on 2023-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generation',
            field=models.IntegerField(default=9),
        ),
    ]
